CREATE USER IF NOT EXISTS '$MARIADB_USER_NAME'@'%' IDENTIFIED BY '$MARIADB_USER_PASS';
GRANT ALL PRIVILEGES ON $WP_DB_NAME.* TO '$MARIADB_USER_NAME'@'%' IDENTIFIED BY '$MARIADB_USER_PASS';

-- UPDATE mysql.user SET password=password('$MARIADB_USER_PASS') WHERE user='$MARIADB_USER_NAME';
UPDATE mysql.user SET password=password('$MARIADB_ROOT_PASS') WHERE user='root';

FLUSH PRIVILEGES;